spring:
  datasource: # 데이터 베이스 설정 (MySQL)
    url: jdbc:mysql://localhost:3306/heavyYoung
    username: root
    password: aod37988##
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: # JPA 설정
    hibernate:
      ddl-auto: create-drop
    show-sql: true